services:
  app:
    image: ${IMAGE_NAME}
    container_name: cats-dogs-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/artifacts/model.pt
      - LABELS_PATH=/app/artifacts/labels.json
    restart: unless-stopped
